---
- name: Partition
  hosts: localhost
  become: yes
  tasks: 
  - name: Create New Partition
    parted: 
      device: /dev/sdb
      number: 1
      state: present
      
   - name: Remove Partition
    parted: 
      device: /dev/sdb
      number: 1
      state: absent
      
    - name: Partition of Size 1Gb
    parted: 
      device: /dev/sdb
      number: 1
      state: present
      part_end: 1GiB
